#### Classification

In [2]:
import pandas as pd
import numpy as np

data=pd.read_csv(r"D:\machine_learning\data\titanic_cleaned.csv")
data.shape
 

(891, 25)

In [3]:
data.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [5]:
y=data["Survived"]
x=data.drop("Survived",axis=1)

In [16]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y=train_test_split(x,y,random_state=101,stratify=None)

In [17]:
from sklearn.linear_model import LogisticRegression as LR 
from sklearn.neighbors import KNeighborsClassifier  as KNN
from sklearn.tree import DecisionTreeClassifier as DT

In [21]:
model1=LR()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10],model1.score(valid_x,valid_y)

D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1], dtype=int64), 0.757847533632287)

In [22]:
model2=KNN()
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10],model2.score(valid_x,valid_y)

(array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0], dtype=int64), 0.6860986547085202)

In [26]:
model3=DT(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10],model3.score(valid_x,valid_y)

(array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64), 0.7443946188340808)

In [36]:
from statistics import mode
final_pred=np.array([])
for i in range(len(valid_x)):
    final_pred=np.append(final_pred,mode([pred1[i],pred2[i],pred3[i]]))

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(valid_y,final_pred)

0.757847533632287

In [38]:
accuracy_score(valid_y,pred1),accuracy_score(valid_y,pred2),accuracy_score(valid_y,pred3)

(0.757847533632287, 0.6860986547085202, 0.7443946188340808)

#### Regression

In [39]:
data=pd.read_csv(r"D:\machine_learning\data\big_mart_sale_cleaned.csv")
data.shape

(8523, 46)

In [40]:
data.head()

Item_Weight  Item_Visibility  Item_MRP  Outlet_Establishment_Year  \
0         9.30         0.016047  249.8092                       1999   
1         5.92         0.019278   48.2692                       2009   
2        17.50         0.016760  141.6180                       1999   
3        19.20         0.000000  182.0950                       1998   
4         8.93         0.000000   53.8614                       1987   

   Item_Outlet_Sales  Item_Fat_Content_LF  Item_Fat_Content_Low Fat  \
0          3735.1380                    0                         1   
1           443.4228                    0                         0   
2          2097.2700                    0                         1   
3           732.3800                    0                         0   
4           994.7052                    0                         1   

   Item_Fat_Content_Regular  Item_Fat_Content_low fat  Item_Fat_Content_reg  \
0                         0                         0                     0   
1                         1                         0                     0   
2                         0                         0                     0   
3                         1                         0                     0   
4                         0                         0                     0   

   ...  Outlet_Size_High  Outlet_Size_Medium  Outlet_Size_Small  \
0  ...                 0                   1                  0   
1  ...                 0                   1                  0   
2  ...                 0                   1                  0   
3  ...                 0                   0                  0   
4  ...                 1                   0                  0   

   Outlet_Location_Type_Tier 1  Outlet_Location_Type_Tier 2  \
0                            1                            0   
1                            0                            0   
2                            1                            0   
3                            0                            0   
4                            0                            0   

   Outlet_Location_Type_Tier 3  Outlet_Type_Grocery Store  \
0                            0                          0   
1                            1                          0   
2                            0                          0   
3                            1                          1   
4                            1                          0   

   Outlet_Type_Supermarket Type1  Outlet_Type_Supermarket Type2  \
0                              1                              0   
1                              0                              1   
2                              1                              0   
3                              0                              0   
4                              1                              0   

   Outlet_Type_Supermarket Type3  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  

[5 rows x 46 columns]

In [41]:
y=data["Item_Outlet_Sales"]
x=data.drop("Item_Outlet_Sales",axis=1)

In [43]:
from sklearn.model_selection import train_test_split
train_x,valid_x,train_y,valid_y=train_test_split(x,y,random_state=101,shuffle=False)

In [44]:
from sklearn.linear_model import LinearRegression as LR
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.tree import DecisionTreeRegressor as DT

In [52]:
model1=LR()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10],model1.score(valid_x,valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]),
 0.5551582433748833)

In [55]:
model2=KNN(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10],model2.score(valid_x,valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]),
 0.5007936087911619)

In [56]:
model3=DT(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10],model3.score(valid_x,valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]),
 0.5735111622038214)

In [62]:
from statistics import mean
final_pred=np.array([])
for i in range(len(valid_x)):
    final_pred=np.append(final_pred,mean([pred1[i],pred2[i],pred3[i]]))


In [63]:
from sklearn.metrics import r2_score

In [68]:
r2_score(valid_y,final_pred)

0.5761404444862531

In [69]:
r2_score(valid_y,final_pred),r2_score(valid_y,pred2),r2_score(valid_y,pred3)

(0.5761404444862531, 0.5007936087911619, 0.5735111622038214)

#### Weighted Averaging

In [70]:
from statistics import mean
final_pred=np.array([])
for i in range(len(valid_x)):
    final_pred=np.append(final_pred,mean([pred1[i],pred1[i],pred2[i],pred3[i],pred3[i]]))


In [71]:
from sklearn.metrics import r2_score

In [72]:
r2_score(valid_y,final_pred)

0.5810653547568736

In [73]:
r2_score(valid_y,final_pred),r2_score(valid_y,pred2),r2_score(valid_y,pred3)

(0.5810653547568736, 0.5007936087911619, 0.5735111622038214)

#### Rank Averaging

In [74]:
m1_score=model1.score(valid_x,valid_y)
m2_score=model2.score(valid_x,valid_y)
m3_score=model3.score(valid_x,valid_y)
m1_score,m2_score,m3_score

(0.5551582433748833, 0.5007936087911619, 0.5735111622038214)

In [78]:
index=[1,2,3]
valid_r2=[m1_score,m2_score,m3_score]

rank_eval=pd.DataFrame({"Score":valid_r2},index=index)
rank_eval

Score
1  0.555158
2  0.500794
3  0.573511

In [80]:
sorted_rank=rank_eval.sort_values("Score")
sorted_rank

Score
2  0.500794
1  0.555158
3  0.573511

In [81]:
sorted_rank["rank"]=[i for i in range(1,4)]
sorted_rank

Score  rank
2  0.500794     1
1  0.555158     2
3  0.573511     3

In [84]:
sorted_rank["weight"]=sorted_rank["rank"]/sorted_rank["rank"].sum()
sorted_rank

Score  rank    weight
2  0.500794     1  0.166667
1  0.555158     2  0.333333
3  0.573511     3  0.500000

In [87]:
wt_pred1=pred1*float(sorted_rank.loc[[1],["weight"]].values)
wt_pred2=pred2*float(sorted_rank.loc[[2],["weight"]].values)
wt_pred3=pred3*float(sorted_rank.loc[[3],["weight"]].values)
ranked_pred=wt_pred1+wt_pred2+wt_pred3
ranked_pred

array([2331.19418533, 2760.66363737, 1452.6721998 , ..., 1348.78554185,
       1570.52823782, 1268.26795746])

In [88]:
r2_score(valid_y,ranked_pred)

0.5828316440450751